[package]
name = "gl21"
version = "0.1.0"
edition = "2021"
authors = ["David Dunwoody <david.dunwoody@gmail.com>"]

[features]
generate-bindings = ["dep:gl_generator"]

[build-dependencies]
gl_generator = { version = "0.14.0", optional = true }
